---
sudo: false
language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
cache: bundler
gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile
before_install: gem install bundler -v 1.17.2
